"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-01-01 00:00:00

Hand-written (not autogenerated) because this environment has no live MySQL
connection to run `alembic revision --autogenerate` against — but it uses the
same `op.create_table` / SQLAlchemy-driven approach Alembic itself would
produce, not raw SQL DDL, per the project's own rule against hand-written DDL
outside migrations. Before your first real run, it's worth diffing this
against `alembic revision --autogenerate -m "check"` (should produce an empty
migration) to confirm it matches the models exactly.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("student", "second_captain", "third_captain", "teacher", name="userrole"),
            nullable=False,
        ),
        sa.Column("oauth_provider", sa.Enum("google", "facebook", name="oauthprovider"), nullable=True),
        sa.Column("oauth_id", sa.String(255), nullable=True),
        sa.Column("avatar_url", sa.String(500), nullable=True),
        sa.Column("roll_number_hash", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_oauth_id", "users", ["oauth_id"])
    op.create_index("ix_users_roll_number_hash", "users", ["roll_number_hash"])

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=True)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"])
    op.create_index("ix_password_reset_tokens_token_hash", "password_reset_tokens", ["token_hash"], unique=True)

    op.create_table(
        "students",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("roll_number_hash", sa.String(64), nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("height_cm", sa.Float, nullable=False),
        sa.Column("seat_constraints", sa.JSON, nullable=True),
        sa.Column("role", sa.String(30), nullable=False, server_default="student"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_students_user_id", "students", ["user_id"])
    op.create_index("ix_students_roll_number_hash", "students", ["roll_number_hash"])

    op.create_table(
        "complaints",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "category",
            sa.Enum(
                "tiffin_theft", "bribes", "syllabus_bloat", "sports_abuse", "seating_abuse",
                name="complaintcategory",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("evidence_url", sa.String(500), nullable=True),
        sa.Column("anonymized_submitter_ref", sa.String(64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "under_review", "resolved", "dismissed", name="complaintstatus"),
            nullable=False,
            server_default="open",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_complaints_anonymized_submitter_ref", "complaints", ["anonymized_submitter_ref"])

    op.create_table(
        "strikes",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("complaint_id", sa.String(36), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False),
        sa.Column("warning_level", sa.Integer, nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_strikes_complaint_id", "strikes", ["complaint_id"])

    op.create_table(
        "seating_layouts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("grid_config_json", sa.JSON, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "syllabus_requests",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("raw_text", sa.Text, nullable=False),
        sa.Column("filtered_topics_json", sa.JSON, nullable=True),
        sa.Column("study_plan_json", sa.JSON, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("type", sa.Enum("cash", "food", name="ledgerentrytype"), nullable=False),
        sa.Column("amount", sa.Float, nullable=False),
        sa.Column("item_description", sa.String(255), nullable=False),
        sa.Column("logged_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "sos_alerts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("location", sa.String(120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "acknowledged", "resolved", name="sosstatus"),
            nullable=False,
            server_default="active",
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "rulebook_entries",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("rule_text", sa.Text, nullable=False),
        sa.Column("embedding_vector", sa.JSON, nullable=True),
        sa.Column("source_section", sa.String(120), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("rulebook_entries")
    op.drop_table("sos_alerts")
    op.drop_table("ledger_entries")
    op.drop_table("syllabus_requests")
    op.drop_table("seating_layouts")
    op.drop_table("strikes")
    op.drop_table("complaints")
    op.drop_table("students")
    op.drop_table("password_reset_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("users")
